version: "3.7"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: llacaze/redtetris_server
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./server:/app
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: llacaze/redtetris_web_client
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - server
    depends_on:
      - server
    volumes:
      - ./client:/app
